CREATE TABLE  "WEB_USER"   
   ("USER_ID" NUMBER(10,0) NOT NULL ENABLE,   
	"USERNAME" VARCHAR2(255 CHAR),   
	"PASSWORD" VARCHAR2(255 CHAR),
	"EMAIL" VARCHAR2(255 CHAR),
	"FORENAME" VARCHAR2(255 CHAR),
	"SURNAME" VARCHAR2(255 CHAR),	
	PRIMARY KEY ("USER_ID") ENABLE  
   )  
/  

